class PlanDecorator < ApplicationDecorator
  filter_attributes :kids_class_price,
                    :kids_class_price_obc,
                    :kids_class_price_outbounds,
                    :class_price,
                    :class_price_obc,
                    :class_price_outbounds,
                    :kids_class_double_workshop_price,
                    :kids_class_double_workshop_price_obc,
                    :kids_class_double_workshop_price_outbounds,
                    :class_double_workshop_price,
                    :class_double_workshop_price_obc,
                    :class_double_workshop_price_outbounds,
                    :workshop_price,
                    :workshop_price_obc,
                    :workshop_price_outbounds,
                    :kid_workshop_price,
                    :kid_workshop_price_obc,
                    :kid_workshop_price_outbounds,
                    :double_workshop_price,
                    :double_workshop_price_obc,
                    :double_workshop_price_outbounds,
                    :kid_double_workshop_price,
                    :kid_double_workshop_price_obc,
                    :kid_double_workshop_price_outbounds,
                    :with => :number_to_currency
end
